### ISSUE TITLE
Get Kount API into Maven Central

### ISSUE THREAD

**Issue by amezick** [Kount/kount-ris-java-sdk#4]
As I sit here on a technical call with your sales rep, I REALLY want this "coming soon" to become "now".

**Comment by boyankukushev** [comment]
Hey mate!

Unfortunately, the product owners dropped this feature from their task list. You can always build the SDK and start using it right away from your local repo. Just go with a `mvn clean install` in the `kount-ris-sdk` folder and you will be fine. I'll let product owners know that people are interested of this artifact going to Central and I'll keep you posted here.

Cheers,
Boyan

**Comment by amezick** [comment]
Thanks Boyan,
I really hope to avoid having to build this and then manage the releases of the 3rd party library I will barely notice in our local Archiva system.

**Comment by dcarabott** [comment]
Any progress on this issue? Do we still have to build the SDK ourselves?

**Comment by boyankukushev** [comment]
Hey @dcarabott 

Unfortunately, the SDK is still not available as an artifact in Maven Central. However, no major changes are expected soon, so it's safe to build and use it from a local Maven repository.

I'll check again with the project owners to see if they decided to boost this issue's importance on their list.

Cheers,
Boyan

**Comment by dcarabott** [comment]
Thanks @boyankukushev for the reply. 

An alternative would be to use the REST API. Its still available right?

**Comment by boyankukushev** [comment]
Unfortunately, this question is beyond my competence. I'd suggest you check that with the Kount Support team.
Kind regards.
Boyan

**Comment by bingyansa** [comment]
Based on the issue, the JAR is published to Maven central.
The Kount RIS SDK artifact is available and ready to use.

You have to add the artifact in your pom.xml file.

`<dependency>
  <groupId>com.github.kountSdk</groupId>
  <artifactId>kount-ris-sdk</artifactId>
  <version>1.0.3</version>
</dependency>`

Hope it will be helpful for you.
