### ISSUE TITLE
Implement MODE U 

### ISSUE THREAD

**Issue by sam33rdhakal** [Kount/kount-ris-java-sdk#6]
I am using java SDK on the server side for RIS inquiry. I need to update the order details to the RIS transaction so that it appears on Agent Web Console. According to documentation, mode U seems to be the one I should use. But there's no implementation of mode U on SDK. 

I am using the latest SDK (version 6.5.2) from https://github.com/Kount/kount-ris-java-sdk/releases. The InquiryMode class is final and only contains Q, P, W, and J mode. Could you please let me know how to update the transaction so that I could see order details in AWC.

**Comment by boyankukushev** [comment]
Hi, Sameer!

Mode `U` is defined in the `com.kount.ris.util.UpdateMode` and used through `com.kount.ris.Update`. After you get back the transaction ID from Kount (successful `Inquiry`), you should use that value and create a new `Update` request to renew transaction details in the Kount-internal databases (therefore in AWC). Please check the repo wiki and the Kount-provided documentation for more information. Also, Kount have a dedicated team for customer support, you can get more details from them.

Cheers and good luck!
Boyan
